root/users/models.py
"""User model"""
from flask_login import UserMixin
from werkzeug.security import check_password_hash

from root.globals import db, login_manager


@login_manager.user_loader
def load_user(user_id):
    """Load the user object from the user ID stored in the session"""
    return User.objects(pk=user_id).first()


class User(db.Document, UserMixin):

    """User model"""

    username = db.StringField(
        required=True, unique=True, max_length=40, index=True)

    password_hash = db.StringField(required=False, index=True)

    stocks = db.ListField(required=False, index=True)

    def check_password(self, password):
        """Checks that the pw provided hashes to the stored pw hash value"""
        return check_password_hash(self.password_hash, password)

    def add_stock(self, stock):
        '''Add stock to user's stock list'''
        self.stocks.append(stock)
        return

    def delete_stock(self, index):
        '''Delete stock from user's stock list'''
        self.stocks.pop(index)
        return

root/core/views.py
"""Core views"""
from flask import Blueprint, render_template

core = Blueprint("core", __name__)


@core.route("/")
def index():
    """This is the landing page view"""
    return render_template("core/index.html")

root/users/views.py
from flask import (
    Blueprint,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_login import current_user, login_required, login_user, logout_user
from werkzeug.security import generate_password_hash
from root.crawler import grade_stock, stock_info
from root.users.models import User

users = Blueprint("users", __name__)


@users.route("/register", methods=["GET", "POST"])
def register():
    """Registers the user with username and password hash in database"""
    logout_user()
    if request.method == "GET":
        return render_template("users/register.html")

    username = request.form.get("username")
    password = request.form.get("password")

    result = User.objects(username=username).first()
    print(result, username, password)
    # check the username is available and put the data in MongoDB
    if result != None:
        flash("The username has been registered!")
        return render_template("users/register.html")
        # return redirect("/error?msg=Sorry, this username has been registered.")
    password_hash = generate_password_hash(password)
    user = User(
        username=username,
        password_hash=password_hash,
    )
    user.save()
    flash("Thanks for registering!")
    login_user(user)
    flash(f"Welcome {user.username}!")
    return redirect(url_for("users.stock"))


@users.route("/login", methods=["GET", "POST"])
def login():
    """Logs the user in through username/password"""
    logout_user()
    if request.method == 'GET':
        return render_template("users/login.html")

    username = request.form.get("username")
    password = request.form.get("password")

    result = User.objects(username=username).first()

    print(result, username, password)
    # check the username is available and put the data in MongoDB
    if result != None and result.check_password(password):
        user = result
        login_user(user)
        flash(f"Welcome {user.username}!")
        return redirect(url_for("users.stock"))
    flash("Invalid Username and/or Password. Please try again.")
    return render_template("users/login.html")


@users.route("/stock", methods=["GET", "POST"])
@login_required
def stock():
    '''Change the URL and render users/stock.html'''
    return render_template("users/stock.html")


@users.route("/crawler", methods=["POST"])
@login_required
def crawler():
    '''Call crawler to search the stock'''
    stock_no = request.form.get("stock_number")
    year = request.form.get("year")
    quarter = request.form.get("quarter")
    date = year+quarter
    # current_user表 現在login的user object

    stock_data = grade_stock.stock_grade(stock_no, date)
    if stock_data["grade"] != None:
        current_user.add_stock(stock_data)
        current_user.save()
    else:
        flash(f'Sorry,the data center refuted your request because you may crawl too frequently or the data you search is not available. Try another one or use the "Input Test Cases" below.')
    return redirect(url_for("users.stock"))


@users.route("/delete", methods=["POST"])
@login_required
def delete():
    '''Delete stock in user's stock list'''
    stock_no = request.args.get("stock_no", None)
    stock_quarter = request.args.get("stock_quarter", None)

    for index, stock in enumerate(current_user.stocks):
        no = stock.get("no")
        date = stock.get("date")
        if no == stock_no and date == stock_quarter:
            current_user.delete_stock(index)
            break
    current_user.save()
    return redirect(url_for("users.stock"))


@users.route("/test_case", methods=["POST"])
@login_required
def test_case():
    '''Input the test cases'''
    stock_cases = stock_info.test_case()
    for case in stock_cases:
        current_user.add_stock(case)
    current_user.save()
    return redirect(url_for("users.stock"))


@users.route("/sort", methods=["POST"])
@login_required
def sort_stock():
    '''Sort stocks by grade'''

    new = sorted(current_user.stocks, key=lambda stock: stock['grade'])
    print(new)
    current_user.stocks = new
    current_user.save()
    return redirect(url_for("users.stock"))


@users.route("/logout")
@login_required
def logout():
    """Log out the current user"""
    logout_user()
    flash("You have logged out.")
    return redirect(url_for("users.login"))


# ----------------------------------------------------------------------------
# HELPER METHODS
# ----------------------------------------------------------------------------

root/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% include "core/bootstrap.html" %}
    <title>Shen's Stock Selection</title>
  </head>
  <body>
    {% include 'core/navbar.html' %} {% include 'core/flash_messages.html' %}
    <br />
    {% block content %}{% endblock content %}
    <br /><br />
  </body>
</html>

root/templates/core/bootstrap.html
<!-- We are importing bootstrap4 CDNs to make our pages look pretty -->
<!-- Bootstrap4 consists of a Stylesheet and 3 javascript files -->

<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
  integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
  crossorigin="anonymous"
/>

<script
  src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
  crossorigin="anonymous"
></script>
<script
  src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
  integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
  crossorigin="anonymous"
></script>
<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
  integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
  crossorigin="anonymous"
></script>

root/templates/core/flash_messages.html
{% with messages = get_flashed_messages() %} {% if messages %}
<div class="container">
  {% for message in messages %}
  <div
    class="text-center alert alert-primary alert-dismissible fade show"
    role="alert"
  >
    {{ message }}
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endfor %}
</div>
{% endif %} {% endwith %}

root/templates/core/index.html
{% extends "core/base.html" %} {% block content %}
<div class="container text-center">
  <div class="jumbotron jumbotron-fluid">
    <h1 class="display-4">Welcome to Shen's Stock Selection!</h1>
    <p class="lead">
      In this platform, you can evaluate the stocks you select by Profitability
      Matrix.
    </p>
  </div>
</div>
{% endblock content %}

root/templates/core/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <!-- Brand: links to index page -->
    <a class="navbar-brand" href="{{ url_for('core.index') }}"
      >Shen's Stock Selection</a
    >
    <!-- Nav links (will collapse if screen size shrinks) -->
    <div class="collapse navbar-collapse" id="navbarDropdown">
      <div class="navbar-nav">
        {% if current_user.is_authenticated %}
        <a class="nav-item nav-link" href="{{ url_for('users.stock') }}"
          >Stocks</a
        >
        <a class="nav-item nav-link" href="{{ url_for('users.logout') }}"
          >Logout</a
        >
        {% else %}
        <a class="nav-item nav-link" href="{{ url_for('users.login') }}"
          >Login</a
        >
        <a class="nav-item nav-link" href="{{ url_for('users.register') }}"
          >Register</a
        >
        {% endif %}
      </div>
    </div>
  </div>
</nav>

root/templates/users/login.html
{% extends "core/base.html" %} {% block content %}

<div class="container text-center">
  <h1>Returning Users</h1>
  <h3>Login with your username and password</h3>

  <form action="{{ url_for('users.login') }}" method="post">
    <div class="form-group">
      <label for="text">Username</label>
      <input
        type="text"
        name="username"
        class="form-control"
        placeholder="Username"
      />
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Password</label>
      <input
        type="password"
        name="password"
        class="form-control"
        placeholder="Password"
      />
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock content %}

root/templates/users/register.html
{% extends "core/base.html" %} {% block content %}

<div class="container text-center">
  <h1>Register</h1>
  <h3>Create account with username and password</h3>

  <form action="{{ url_for('users.register') }}" method="post">
    <div class="form-group">
      <label for="text">Username</label>
      <input
        type="text"
        name="username"
        class="form-control"
        placeholder="Username"
      />
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Password</label>
      <input
        type="password"
        name="password"
        class="form-control"
        placeholder="Password"
      />
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock content %}

root/templates/users/stock.html
{% extends "core/base.html" %} {% block content %}
<div class="container">
  <div class="jumbotron jumbotron-fluid">
    <!-- current_user會紀錄data -->
    <h1 class="display-4">&thinsp;&thinsp;Hello, {{current_user.username}}</h1>
    <p class="lead">
      &emsp;Search your stock by stock number and ending quarter of a year.
    </p>
    <hr class="my-4" />
    <div class="container">
      <form action="{{ url_for('users.crawler') }}" method="post">
        <div class="form-group">
          <input
            type="test"
            name="stock_number"
            class="form-control"
            placeholder="Stock's number (e.g. 2330)"
          />
        </div>
        <div class="row">
          <div class="col">
            <input
              type="text"
              name="year"
              class="form-control"
              placeholder="Year (e.g. 2022)"
            />
          </div>
          <div class="col">
            <input
              type="number"
              name="quarter"
              class="form-control"
              placeholder="Quarters (1,2,3,4)"
              min="1"
              max="4"
            />
          </div>
        </div>
        <br />
        <center>
          <button type="submit" class="btn btn-primary">Submit</button>
        </center>
      </form>
    </div>

    <hr class="my-4" />
    <form action="{{ url_for('users.test_case')}}" method="post">
      <center>
        <button type="submit" class="btn btn-secondary btn-sm">
          Input Test Cases
        </button>
      </center>
    </form>
    <br />
    <form action="{{ url_for('users.sort_stock')}}" method="post">
      <center>
        <button type="submit" class="btn btn-secondary btn-sm">
          Sort by Grades
        </button>
      </center>
    </form>
    <p class="lead">&emsp;Here are your stocks.</p>

    <div class="container">
      <ul class="list-group">
        {% for stock in current_user.stocks %}
        <form
          action="{{ url_for('users.delete', stock_no = stock['no'], stock_quarter = stock['date']) }}"
          method="post"
        >
          <li class="list-group-item">
            No.{{stock["no"]}}&emsp;Name:{{stock["name"]}}&emsp;Quarter:{{stock["date"]}}&emsp;ROE:{{stock["roe"]}}%
            &emsp;Free Cashflow:{{stock["fcf"]}}億&emsp;
            Grade:{{stock["grade"]}}&emsp;&emsp;&emsp;&emsp;
            <button type="submit" class="btn btn-danger">Delete</button>
          </li>
        </form>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>
{% endblock content %}